name: Rust

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

env:
  CARGO_TERM_COLOR: always
  APP_KEY: ${{ secrets.APP_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
